### ISSUE TITLE
Failed to precompile HttpServer (v0.5-rc1)

### ISSUE THREAD

**Issue by asbisen** [JuliaWeb/HttpServer.jl#102]
I am having a difficult time loading `HttpServer.jl` on `v0.5-rc1`. What I might be missing? I have tried the latest `tag` as well as `master`

``` julia
julia> using HttpServer
INFO: Precompiling module HttpServer...
ERROR: Failed to precompile HttpServer to /Users/abisen/.julia/lib/v0.5/HttpServer.ji
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:364

```

**Comment by quinnj** [comment]
I think this is a known issue on v0.5-rc1+0, you need v0.5-rc1+1 instead, right @tkelman ?

**Comment by asbisen** [comment]
thanks you are right I was able to load with `0.5.0-rc1+1`
