### ISSUE TITLE
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HttpServer.jl#106]
I'm not sure how to track this down, but I created a web app using HttpServer and WebSockets.

Everything works great when when I run it on localhost. When I run it out in the open on an Azure VM, it still works fine. Everything is working including WebSockets on the web, BUT... I am getting the following error spewing onto the REPL every couple seconds:

``` julia
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)
in yieldto(::Task, ::ANY) at .\event.jl:136
in wait() at .\event.jl:169
in wait(::Condition) at .\event.jl:27
in wait_readnb(::TCPSocket, ::Int64) at .\stream.jl:303
in eof(::TCPSocket) at .\stream.jl:58
in process_client(::HttpServer.Server, ::HttpServer.Client{TCPSocket}, ::Bool) at C:\Users\eric\.julia\v0.5\HttpServer\src\HttpServer.jl:376
in (::HttpServer.##8#10{HttpServer.Server,Bool})() at .\task.jl:360
```

Again, the error does not appear when running on local host. Running on the web via Azure VM, everything still seems to work, but that errors spews to the REPL.

Any ideas?

**Comment by jingpengwu** [comment]
My program runs in local machines, when I move to AWS EC2 and use S3 storage, I got this error too!

**Comment by EricForgy** [comment]
Hehe. I almost said "Me too!" until I realized I posted the original issue 😂
