### ISSUE TITLE
Incomplete TLS negotiation causes total denial of service

### ISSUE THREAD

**Issue by joshbode** [JuliaWeb/HttpServer.jl#114]
It is possible to cause a total denial of service for an SSL-enabled HttpServer by holding a single connection open without initiating the TLS handshake. While handling a request is performed via `@async`, I imagine this issue is occurring since establishing the TLS connection is single-threaded.

I've seen this on a server I've got in the wild (Linux) where it is being consistently DOSed daily with this issue (not sure if due to malice or otherwise). I will be putting the server behind nginx, at the very least.

Basic HTTPS server:
```julia
#! /usr/bin/env julia

using HttpServer
using MbedTLS

handler = HttpHandler() do req::Request, res::Response
    res.data = "Hello, World!"
    res.status = 200
    res
end

server = Server(handler)

cert = MbedTLS.crt_parse_file("server.crt")
key = MbedTLS.parse_keyfile("server.key")

run(server, host=ip"127.0.0.1", port=5000, ssl=(cert, key))
```

Run the server:
```bash
$ openssl req -x509 -nodes -subj /CN=localhost -days 365 -newkeyrsa:2048 -keyout server.key -out server.crt
$ chmod +x hello.jl
$ ./hello.jl
Listening on 127.0.0.1:5000...
```

Test the server:
```bash
$ curl -k https://localhost:5000/
Hello, World!
```

Open (and leave open) a connection to the server:
```bash
$ nc localhost 5000
```

Attempt to make a connection:
```bash
$ curl -vk https://localhost:5000/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
```
which never returns.

Tested on OS X, Julia 0.5:
```julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753* (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7550  @ 2.26GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, penryn)

julia> Pkg.status("MbedTLS")
 - MbedTLS                       0.4.3

julia> Pkg.status("HttpServer")
 - HttpServer                    0.1.7
```

**Comment by quinnj** [comment]
This is currently handled correctly in HTTP.jl (current master) using the following server:
```julia
#! /usr/bin/env julia

using HTTP
using MbedTLS

cert = joinpath(Pkg.dir("HTTP"), "test/cert.pem")
key = joinpath(Pkg.dir("HTTP"), "test/key.pem")

server = HTTP.serve(host=ip"127.0.0.1", port=5000, cert=cert, key=key)
```

**Comment by joshbode** [comment]
Ahh - good to hear :)

Is HTTP.jl ready to start using, and will it ultimately deprecate HttpServer.jl (and Requests.jl, etc)?

In the meantime, I've worked around the issue by reverse-proxying `HttpServer` (serving HTTP, not HTTPS) behind nginx (with SSL) via `proxy_pass`.

**Comment by quinnj** [comment]
Yes, I think HTTP.jl is ready to start using. I'd still consider it somewhat beta, but a lot of the low-hanging fruit has been cleared away and IMO, it's more functional and stable than Requests/HttpServer.jl at this point. I don't think it's a bad idea to leave nginx out in front, given it's maturity, but the server code in HTTP.jl should be a definite upgrade from HttpServer.jl.
