### ISSUE TITLE
Async server so REPL works via accept_nonblock()

### ISSUE THREAD

**Issue by kungfooman** [JuliaWeb/HttpServer.jl#120]
Hi all, I just needed to run a WebSockets.jl server, but running other functions at 20fps aswell. This is pretty easy in nodejs, but I couldn't find any support in HttpServer.jl

I ended up rewriting the logic a bit in HttpServer.jl, so it is using `Base.accept_nonblock` now:

```
id_pool = 0 # Increments for each connection
""" Handle HTTP request from client """
function handle_http_request(server::Server)
	global id_pool
	websockets_enabled = server.websock != nothing
	
	sock = TCPSocket()
		
	try
		#sock = accept(server.http.sock)
		
		err = Base.accept_nonblock(server.http.sock, sock)
		#print("Accept nonblock ret: ", err, "\n")
		if err != 0
			
			#sock = TCPSocket()
			return;
		end
	catch e
		if !isopen(server.http.sock)
			# Server was closed while waiting to accept client. Exit gracefully.
			return
		end
		throw(e)
	end
	client = Client(id_pool += 1, sock)
	client.parser = ClientParser(message_handler(server, client, websockets_enabled))
	@async process_client(server, client, websockets_enabled)
end
```

Then this method needs to be called all the time, which I did this way:

```
Timer(function(timer)
	HttpServer.handle_http_request(server)
	Com_Frame() # my stuff which needs to run at 20fps
	#print("Hai!\n")
end, 0, 0.05)
```

IMO this kind of functionality should be something standardish, or maybe im just node.js spoiled.

Pros:
 - REPL works, even when the server went into block mode via accept()

Contra:
 - The "client accepting" has now the 0.05 seconds delay. I don't know how to immediatly set a callback when a client is ready.

Any thoughts on this? Would be nice if something like this would be standard, but "properly" implemented without the contra.

**Comment by vtjnash** [comment]
Julia handles everything with `@async accept()` (or `@async handle_http_request()`, etc). This saves the need for the complexity of the node.js approach.
