### ISSUE TITLE
Enable appveyor for this repo

### ISSUE THREAD

**Issue by davidanthoff** [JuliaWeb/HttpServer.jl#127]
Could someone enable appveyor under the JuliaWeb account for this repo? There is an appveyor running [here](https://ci.appveyor.com/project/malmaud/httpserver-jl/), but it is in @malmaud's name and therefore not showing up on PRs etc.

@aviks Is that something you might be able to do?

**Comment by aviks** [comment]
I tried adding it, but it's running on a url under my name: https://ci.appveyor.com/project/aviks/httpserver-jl

I've never understood how appveyor works with org accounts :(

**Comment by aviks** [comment]
Although, it does seem to be showing on the PR. Ah... the mysteries.

**Comment by davidanthoff** [comment]
Well, I guess that is good enough ;) Yeah, same here, never understood org accounts with appveyor. They do exist, though, because I am part of one for a completely unrelated project...
