### ISSUE TITLE
Can't install on Manjaro using Julia 0..6.2

### ISSUE THREAD

**Issue by NaelsonDouglas** [JuliaWeb/HttpServer.jl#131]
I'm trying to install HttpServer on Manjaro using Julia 0.6.2, but I'm unable to build the package

Here's the error log:
https://asciinema.org/a/5LxAAQGQpYoKT2iOOvy6a4eeH

**Comment by ararslan** [comment]
I don't believe HttpServer is being actively maintained at the moment; [HTTP](https://github.com/JuliaWeb/HTTP.jl) is a more general replacement for HttpServer and should hopefully work fine on Manjaro.

**Comment by NaelsonDouglas** [comment]
Makes sense. I'm already migrating the code for HTTP.

Thanks.
