### ISSUE TITLE
Memory usage increasing as number of requests increases

### ISSUE THREAD

**Issue by cmpitg** [JuliaWeb/HttpServer.jl#30]
Hi,

I first reported this on [Morsel](https://github.com/JuliaLang/Morsel.jl/issues/24) before I realized it traced back to HttpServer.

With this simple HTTP server taken from README:

```julia
using HttpServer

http = HttpHandler() do req::Request, res::Response
    Response("Hello World")
end

http.events["error"]  = (client, err) -> println(err)
http.events["listen"] = (port) -> println("Listening on $port...")

server = Server(http)
run(server, 8000)
```

I noticed there's an increase in memory usage each time it received new requests (monitored with htop). Apache Bench showed it clearly:

```sh
ab -n 10000 -c 5 http://0:8000/
```

On my machine (Debian Jessie 64-bit, Julia 0.3.0+6 built from source), it reached 164.9 MB from 115.4 MB after the first Apache Bench run and kept increasing. Following @IainNZ's advice, I added a route to trigger GC like so:

```julia
    if ismatch(r"^/gc/", req.resource)
        gc()
        Response("GC-ed")
    else
        Response("Hello World")
    end
```

But memory usage stayed the same even when the GC has finished. Any idea?

Duong

**Comment by malmaud** [comment]
I'm thinking of looking into this again - before I do, does anyone have any additional insights since last year?

**Comment by malmaud** [comment]
Hmm, on my system (OS X 10.10), the memory consumed by the server doesn't go above 160 mb even after 50000 requests. I'm going to assume that some change in either Julia or this package has fixed the leak, but please reopen if you're still seeing this.

Here's the Julia version I'm using:
```
julia> versioninfo()
Julia Version 0.5.0-dev+427
Commit 40cf531 (2015-09-24 01:23 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.4.0)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-svn

```
