### ISSUE TITLE
AB times out on Osx 10.9.4

### ISSUE THREAD

**Issue by itsmontoya** [JuliaWeb/HttpServer.jl#40]
Trying to run a simple httpServer
```julia
using HttpServer

http = HttpHandler() do req::Request, res::Response
    Response("Hello World")
end

http.events["error"]  = (client, err) -> println(err)
http.events["listen"] = (port) -> println("Listening on $port...")

server = Server(http)
run(server, 8000)
```

I receive the following error
```
apr_poll: The timeout specified has expired (70007)
```

Loading the port from a browser and curl seems to work fine.

**Comment by dfdx** [comment]
AB doesn't work for me either with exactly the same behavior (timeout after 30 seconds). Technical details: 

Linux Mint 17.1 (with kernel 3.19)
Julia 0.4.0-dev+3661

**Comment by mxposed** [comment]
I had the same issue with `ab`, however closing the connection in `HttpServer.jl` fixed it, so now `ab` works. I will look into why this happens deeper and report here

**Comment by IainNZ** [comment]
If this still occurs on master, please reply.
