### ISSUE TITLE
for Julia 0.4: rename to HTTPServer

### ISSUE THREAD

**Issue by garborg** [JuliaWeb/HttpServer.jl#43]
Make naming of 'HTTP' packages (HTTPClient.jl, HttpServer.jl, HttpParser.jl, and HttpCommon.jl) consistent. Timing to mirror timing of [rename of Color.jl](https://github.com/JuliaLang/Color.jl/issues/56) to Colors.jl.

**Comment by IainNZ** [comment]
Closing in favour of https://github.com/JuliaWeb/Roadmap/issues/3
