### ISSUE TITLE
where is root  dir on my hard disk ?

### ISSUE THREAD

**Issue by paulanalyst** [JuliaWeb/HttpServer.jl#49]
where is root  dir on my hard disk ?
I have install julia on win 7 on D disk. and some path of julia are on C/users/.../.Julia...
where is root  dir on my hard disk ?
Wher I must put the file index.html ?
Paul

**Comment by aviks** [comment]
HTTPServer.jl is not a traditional static web server. It is basically a framework to listen to  and parse HTTP request. The response needs to be coded by the programmer. 

So, specifically, the root dir is where ever your implementation of the HTTPResponseHandler needs them to be.

**Comment by aviks** [comment]
Actually, a Handler for static files exists in [Meddle.jl](https://github.com/JuliaWeb/Meddle.jl)

https://github.com/JuliaWeb/Meddle.jl/blob/master/src/Meddle.jl#L137-L153

As you can see, the `FileServer` function takes the root directory as a parameter. Usage instructions are at  https://github.com/JuliaWeb/Meddle.jl/blob/master/src/Meddle.jl#L16-L27

**Comment by paulanalyst** [comment]
Thx:)
Paul
W dniu 2015-03-03 o 15:32, Avik Sengupta pisze:
