### ISSUE TITLE
Access to client IP

### ISSUE THREAD

**Issue by one-more-minute** [JuliaWeb/HttpServer.jl#50]
It's important for me to be able to access the client's IP, but I don't see a way to do get it. Maybe this could be integrated into `Request` somehow?

**Comment by wildart** [comment]
Currently, Julia does not have implemented functionality to determine client's socket address. I posted PR [#11012](https://github.com/JuliaLang/julia/pull/11012) which would add this functionalty. As soon as it's accepted, it will be possible to setup `Remote-Address` or `X-Forwarded-For` headers.

**Comment by malmaud** [comment]
Closing in favor of https://github.com/JuliaLang/julia/pull/11012

**Comment by malmaud** [comment]
https://github.com/JuliaLang/julia/commit/c16d17440c68d500a9f419ed710e633356a886d6 is merged now

**Comment by one-more-minute** [comment]
Awesome, nice work @wildart
