### ISSUE TITLE
TLS Server example

### ISSUE THREAD

**Issue by androck** [JuliaWeb/HttpServer.jl#51]
Hi,
I couldn´t find any TLS HTTPServer example, nor couldn´t get it running by myself via "function run_https(server::Server, auth::GnuTLS.CertificateStore, args...)"
Could you please add an example?

**Comment by wildart** [comment]
See #56. It has example.

**Comment by androck** [comment]
Thanks!

**Comment by wildart** [comment]
Now in `master`.

**Comment by androck** [comment]
Yes, works fine, thanks.
