### ISSUE TITLE
https example failing

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/HttpServer.jl#57]
Hi there,

I'm having trouble running examples/https.jl.
After creating a self-signed certificate as per the example, and  executing the last line ```run(server, port=8000, ssl=cert_store)``` things seem OK. No errors  yet.

When I navigate to https://0.0.0.0:8000 I get the error:
```Error establishing SSL connection: ErrorException("stream is closed or unusable")```

I'm using Debian 8, Julia 0.3.9.

Any ideas?

Jock

**Comment by wildart** [comment]
What version of GnuTLS do you use? Have you tried to update packges?

**Comment by JockLawrie** [comment]
I have GnuTLS 2.12.20 which ships with Debian 8, and GnuTLS.jl 0.0.4.

**Comment by JockLawrie** [comment]
Yes I updated packages yesterday and the error still occurred.
Cheers,
Jock

**Comment by JockLawrie** [comment]
Bit of a long shot, but one possible problem is file permissions.
I have rw access to the crt/csr/key files. I would have thought this would be sufficient, and I can't seem to run julia as root.
Just putting it out there in case this sparks any related ideas.

**Comment by JockLawrie** [comment]
Problem solved.
Having reinstalled gnutls (not GnuTLS.jl) and libnettle things are working fine.
Issue ready to be closed.
