### ISSUE TITLE
OSX error on example

### ISSUE THREAD

**Issue by marcstein** [JuliaWeb/HttpServer.jl#61]
Hi,

I'm just running the basic example from the GitHub page

using HttpServer

http = HttpHandler() do req::Request, res::Response
    Response( ismatch(r"^/hello/",req.resource) ? string("Hello ", split(req.resource,'/')[3], "!") : 404 )
end

server = Server( http )
run( server, 8000 )

It launches the server instance but immediately throws the following error:

Listening on 0.0.0.0:8000...
ERROR: type cannot be constructed
 in ClientParser at /Users/marcstein/.julia/v0.3/HttpServer/src/RequestParser.jl:133
 in handle_http_request at /Users/marcstein/.julia/v0.3/HttpServer/src/HttpServer.jl:224
 in run at /Users/marcstein/.julia/v0.3/HttpServer/src/HttpServer.jl:305
 in run at /Users/marcstein/.julia/v0.3/HttpServer/src/HttpServer.jl:309

I'm running Julia 0.3.11 on OSX El Capitan Beta 7. Has anyone gotten this to work on El Capitan?

**Comment by malmaud** [comment]
This will be fixed in the next few days - thanks for your patience.

**Comment by malmaud** [comment]
If you run `Pkg.update()`, this will work now. Please reopen if you're still having issues.

**Comment by marcstein** [comment]
Jonathan,

Thank you SO much for the fast solution! That worked perfectly.

Best,

Marc
