### ISSUE TITLE
HttpCommon and HttpServer releases are not in sync

### ISSUE THREAD

**Issue by rohitvarkey** [JuliaWeb/HttpServer.jl#66]
The new `HttpCommon` release of `v0.2.1` expects `FileResponse` and `mimetypes` to be moved to `HttpServer` in https://github.com/JuliaWeb/HttpCommon.jl/commit/b6821d860395433cb3db2a3e6880144c18a05399.
But HttpServer does this only in https://github.com/JuliaWeb/HttpServer.jl/commit/8005fe6ff7554d813337b5a5d5487503b80fe1f5, which is not included in the `v0.1.0` release. (https://github.com/JuliaWeb/HttpServer.jl/tree/v0.1.0)

So `Pkg.update()` breaks stuff currently.

**Comment by IainNZ** [comment]
Yes we know. The `v0.1.0` and onward releases are only for pre-release Julia 0.4, so stuff will be break as we try to refactor JuliaWeb into shape. I'm checking tests pass now - if they do, I'll tag a new release of HttpServer.

**Comment by IainNZ** [comment]
As `FileResponse` and `mimetypes` are unexported and undocumented, they may break again until they are officially support (e.g. `mimetypes` might get renamed).

**Comment by rohitvarkey** [comment]
Cool. I'll be closing this now then. :smile:

**Comment by IainNZ** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/3319

**Comment by rohitvarkey** [comment]
Awesome! Thanks!
