### ISSUE TITLE
HttpHandler.handle API suggestion

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/HttpServer.jl#74]
Hi all,

Just wondering what community members think of changing the signature of `HttpHandler.handle` from `f(req, res)` to `f(req)`?

Currently a default response, namely `Response()`, is passed to the handler, which is then modified. Wouldn't it make more sense to simply pass in the request and return the response? From a user's point of view I think this makes the functionality of an application more obvious.

For reference, I currently use the following:

``` julia
function app(req::Request)
    ...    # do stuff here
    res    # Response object
end

server = Server((req, res) -> app(req))    # Boilerplate
run(server, 8000)
```

Thoughts?

**Comment by rened** [comment]
Yes, I was wondering about the same thing - I believe this comes from the fact that the library is modelled after node.js, where the `res` is predefined and has to be used? I am for removing `res`, but don't know enough about HttpServer nor node.js to be able to judge the wider impact this would have.

**Comment by malmaud** [comment]
Yes, that should definitely be done. It just has to be done in a non-breaking way.

**Comment by JockLawrie** [comment]
By non-breaking do you mean accommodating both `f(req, res)` and `f(req)`?

Is this necessary? I'm inclined to pick one and go with it to avoid confusion. Seems now is the time for breaking changes...e.g., `Nettle.jl` has completely changed its API, and of course there's Julia 0.4 itself.

Does anyone know how many packages depend on `HttpServer.jl`?

**Comment by IainNZ** [comment]
One can be deprecated in favour of the other, but not suddenly breaking it would definitely be preferrable - people are using HttpServer for real work out in the world, and all the other churn so far as quite possibly not affected them.

**Comment by JockLawrie** [comment]
Sounds reasonable @IainNZ.
I'm still wondering what the community thinks - is this a good idea? (seems ok to me, but that's just me)

**Comment by malmaud** [comment]
Seems like a great idea to me

**Comment by JockLawrie** [comment]
There seems to be some support for this idea from the developers and no objections. I'll put it to the users and go from there.

**Comment by ssfrr** [comment]
I just came to file a similar issue because I had the same confusion, so this was enlightening. In fact I found a bug where I was setting a status code on the given response and then returning a new string (I guess I was thinking that the returned string was stuffed into the response or something).

My only hesitation would be whether the response argument is useful for middleware or something, but I can't think of an example where that would be true, so I think :+1:.

**Comment by JockLawrie** [comment]
@ssfrr Presumably you were trying to achieve something like this?
```julia
res = Response()
# do stuff here
res.status = some_int
res.data   = some_string
return res
```
The response argument can still be used in middleware (which doesn't exist yet). This issue concerns the outermost handler, the one that initially receives the request.

**Comment by ssfrr** [comment]
Something like that. It's clear now how things work, I just made a bad assumption when first looking at how the response stuff worked.

re: middleware, my guess is that a given middleware layer (e.g. for authentication) would look something like:

```julia
function handle_auth(request::Request)
    check_auth(request)
    add_auth_info!(request)
    response = next_layer_handler(request)
    add_auth_headers!(response)
    response
end
```

So aribitrarily-deep middleware nesting should be just fine without passing in the request. I guess the question was just whether an outer middleware layer would ever need to do things to the response *before* it's handed to the next layer in, but I don't think so.

**Comment by JockLawrie** [comment]
In that case I'd also pass in the response as an argument and modify it, much like in the now-deprecated Meddle.jl.

FYI - you might want to keep an eye on [this repo](https://bitbucket.org/jocklawrie/skeleton-webapp.jl). It serves as a learning resource, a basis for some web services at my work, and an environment to try out API ideas like the one you're considering.

See Examples 5 and 6 in docs/outline. I have written Example 5 and will commit it next week. It touches on the middleware API issue you've raised, in this case validating a secure session cookie. Example 6 will follow in November. Suggestions always welcome.
