### ISSUE TITLE
Stopping HttpServer without quiting Julia

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HttpServer.jl#82]
Is this possible?

If I am working on some code that involves launching an HttpServer, it would be nice if I could close the socket (if that is the right way to say that) without having to kill Julia.

If it is easy to implement, I could have a go at a PR, but some hints would be welcome as I'm just learning this stuff :)

Edit: Starting to dig into this a little...

When you "run", you need to provide a "Server" object. A Server object has a HttpHandler member object, which in turn has a Base.TCPServer object. If there is an easy way to stop that TCPServer, then a "close" method should be possible (?)

Edit^2: I found that TCPServer inherits from LibuvServer and in Base.streams.jl, we can find this encouraging method:

    function close(stream::Union{LibuvStream, LibuvServer})
        if isopen(stream) && stream.status != StatusClosing
            ccall(:jl_close_uv,Void, (Ptr{Void},), stream.handle)
            stream.status = StatusClosing
        end
        nothing
    end

Edit^3: I was able to close the HttpServer, but it did not die gracefully. Any ideas?

    Listening on 0.0.0.0:8000...
    
    julia> http
    HttpServer.HttpHandler((anonymous function),Base.TCPServer(active),Dict("error"=>(anonymous function),"listen"=>(anonymous function)))
    
    julia> tcp = http.sock
    Base.TCPServer(active)
    
    julia> close(tcp)
    
    julia> ERROR (unhandled task failure): accept: software caused connection abort (ECONNABORTED)
     in accept at stream.jl:1063
     in handle_http_request at C:\Users\Eric Forgy\.julia\v0.4\HttpServer\src\HttpServer.jl:232
     in run at C:\Users\Eric Forgy\.julia\v0.4\HttpServer\src\HttpServer.jl:339
     in run at C:\Users\Eric Forgy\.julia\v0.4\HttpServer\src\HttpServer.jl:343
     in anonymous at task.jl:447
    julia> tcp
    Base.TCPServer(closed)

**Comment by EricForgy** [comment]
When I close the TCPServer, the HttpServer does not die gracefully. One reason is handle_http_request:

    """ Handle HTTP request from client """
    function handle_http_request(server::Server)
        id_pool = 0 # Increments for each connection
        websockets_enabled = server.websock != nothing
        while true # handle requests, Base.wait_accept blocks until a connection is made
            client = Client(id_pool += 1, accept(server.http.sock))
            client.parser = ClientParser(message_handler(server, client, websockets_enabled))
            @async process_client(server, client, websockets_enabled)
         end
    end

One possible solution I can think of is instead of 

    while true

we make it

    while server.sock.status == StatusActive

Is that a bad idea?

**Comment by cwiese** [comment]
Agreed, what a pain using the REPL and Crtl-C then quit() every time you test!  Otherwise, the port is "IN USE"

**Comment by EricForgy** [comment]
I'm working on it and hopefully have a PR ready soon. I can make an HttpServer shutdown gracefully now, but doing some final testing.
