### ISSUE TITLE
Downstream error from Blink.jl

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaWeb/HttpServer.jl#86]
```
ArgumentError: cannot convert NULL to string
 in on_header_value at /home/tom/.julia/v0.4/HttpServer/src/RequestParser.jl:60
```

Ref: JunoLab/Blink.jl#22

**Comment by tbreloff** [comment]
I think these are all related as well:

https://github.com/JuliaWeb/HttpParser.jl/issues/42
https://github.com/JuliaWeb/HttpParser.jl/issues/32
https://github.com/JuliaWeb/HttpParser.jl/pull/36
https://github.com/JuliaWeb/HttpServer.jl/issues/81

And this comment has the same error:
https://github.com/JuliaWeb/HttpParser.jl/issues/32#issuecomment-117428119

I'm going to try using that PR....

My system is Centos 7 (similar to Fedora, which is where all these errors are popping up)

**Comment by tbreloff** [comment]
I finally solved this.  It was as simple as removing the http_parser libs from `/lib64/libhttp_parser*`!  I'll open an issue at HttpParser.jl to see if there's a way to protect from mismatched libraries in the future.  Feel free to close the issue (I can't)
