### ISSUE TITLE
Can't precompile on Windows 10

### ISSUE THREAD

**Issue by sgt101** [JuliaWeb/HttpServer.jl#90]
@unix_only error at line 221 httpserver.jl

I understand why but given I am trying to use Juno/Atom as my IDE and I'm blocked by this I think that it would be good to flag that this is a dependency issue at the front of the project so that other projects don't pick it up...

**Comment by OxeStone** [comment]
Me too! On Wndows 10, try:
Pkg.test("HttpServer")
you get a 'ERROR: LoadError: invalid doc expression:' I removed the code related to '@unix_only' and the error pops up again.

**Comment by pfitzseb** [comment]
Something like
```
@unix_only begin
  doc""" Start `server` to listen on named pipe/domain socket.

      listen(server::Server, path::AbstractString) Server

      Setup "server" to listen on named pipe/domain socket specified by "path".
  """ ->
  function listen(server::Server, path::AbstractString)
      bind(server.http.sock, path) || throw(ArgumentError("could not listen on path $path"))
      Base.uv_error("listen", Base._listen(server.http.sock))
      event("listen", server, path)
      return server
  end
end
```
should work instead, I think.

**Comment by wildart** [comment]
PR is welcome.

**Comment by OxeStone** [comment]
I still get:
ERROR: LoadError: invalid doc expression: ....
'@unix_only' not documentable. See 'Base.@__doc__' docs for details. .....
ERROR: Base.Pkg.PkgError("HttpServer had test errors") .....

**Comment by OxeStone** [comment]
Update: the above steps work only on Julia 0.4.5 32-bit. I got errors on 0.4.5 64-bit and on both 32-bit and 64-bit of the 0.5 development package.
