### ISSUE TITLE
Add HTTP/2.0?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaWeb/HttpServer.jl#95]
I'm not pressing for it, it's more of a questions, wouldn't it belong here (and elsewhere?)?

[SPDY is "dead", so do not worry about that.]

In case it's already supported, it should be in NEWS file, otherwise could just keep this open in case someone wants to implement later..

**Comment by wildart** [comment]
FYI, https://github.com/sorpaas/HTTP2.jl

**Comment by malmaud** [comment]
A GSOC student is working on it. We'll have it soon.
